Module: NumPy Assignments
Lesson: NumPy

Lesson NUMPY
Assignment 1: Array Creation and Manipulation


1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [5]:
import numpy as np
import random 
array = np.random.randint(1,21,size=(5,5))
print("orignal array")
print(array)

array[2:3]=1
print(array)

orignal array
[[ 2 10  5 19  1]
 [10 11 17  5  1]
 [ 6 15 11  4 16]
 [13  7  1 18 13]
 [12 12 14 13 18]]
[[ 2 10  5 19  1]
 [10 11 17  5  1]
 [ 1  1  1  1  1]
 [13  7  1 18 13]
 [12 12 14 13 18]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [13]:
array2= np.arange(1,17).reshape(4,4)
print(array2)

np.fill_diagonal(array2,0)
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [18]:
array=np.arange(1,37).reshape(6,6)
print(array)

print(array[2:6,2:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[15 16]
 [21 22]
 [27 28]
 [33 34]]


2.Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [26]:
array=np.random.randint(1,26,size=(5,5))
print(array)

border_element=np.concatenate((array[0, :],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print(border_element)

[[ 4 20 11 18 25]
 [12 24 21 24  1]
 [ 2  5 15  2  9]
 [21 18 21 23 25]
 [18 21  2 12 24]]
[ 4 20 11 18 25 18 21  2 12 24 12  2 21  1  9 25]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.



In [28]:
array1=np.random.randint(1,13,size=(3,4))
array2=np.random.randint(1,13,size=(3,4))

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Element-wise addition:
[[ 9 20  5  7]
 [16  5 15  5]
 [20 16 10 14]]
Element-wise subtraction:
[[ 3 -2 -3  3]
 [ 4 -1 -1  3]
 [-2  4  0 -2]]
Element-wise multiplication:
[[18 99  4 10]
 [60  6 56  4]
 [99 60 25 48]]
Element-wise division:
[[2.         0.81818182 0.25       2.5       ]
 [1.66666667 0.66666667 0.875      4.        ]
 [0.81818182 1.66666667 1.         0.75      ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [30]:
array=np.arange(1,17).reshape(4,4)
print(array)

row=np.sum(array,axis=0)
col=np.sum(array,axis=1)
print(row,col)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[28 32 36 40] [10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [37]:
array=np.arange(1,10).reshape(3,3)
print(array)

mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


 Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [41]:
array=np.random.randint(1,10,size=(3,3))
row=np.random.randint(1,10,size=(3,))
print(array)
print(row)

print(array+row)

[[8 7 5]
 [2 9 4]
 [1 5 3]]
[7 2 9]
[[15  9 14]
 [ 9 11 13]
 [ 8  7 12]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [43]:
array=np.random.randint(1,17,size=(4,4))
row=np.random.randint(1,17,size=(4,))
print(array)
print(row)

print(array-row)

[[ 7  9  3  2]
 [ 2 13  3  4]
 [ 8 12  2  5]
 [ 5  8  9 15]]
[ 5  8 13 11]
[[  2   1 -10  -9]
 [ -3   5 -10  -7]
 [  3   4 -11  -6]
 [  0   0  -4   4]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [50]:
array=np.random.randint(1,17,size=(3,3))
print(array)

matrix=np.linalg.det(array)
print(matrix)

inverse = np.linalg.inv(array)
print("Inverse:")
print(inverse)



[[16  5  9]
 [14  8  4]
 [10  3 11]]
304.00000000000006
Inverse:
[[ 0.25       -0.09210526 -0.17105263]
 [-0.375       0.28289474  0.20394737]
 [-0.125       0.00657895  0.19078947]]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [53]:
array1=np.random.randint(1,17,size=(2,3))
array2=np.random.randint(1,17,size=(3,2))

result=np.dot(array1,array2)
print(result)

[[ 61 239]
 [120 278]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).



In [2]:
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [8]:
import numpy as np


array=np.random.randint(1,26,size=(5,5))
print(array)

flatend_array=array.flatten()
print(flatend_array)

reshaped_array = flatend_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

[[17 10 15 13 13]
 [ 6 16 22  4 25]
 [18 14  9 18 22]
 [ 7  9 12 19 21]
 [ 1  2  8 22  2]]
[17 10 15 13 13  6 16 22  4 25 18 14  9 18 22  7  9 12 19 21  1  2  8 22
  2]
Reshaped array:
[[17 10 15 13 13]
 [ 6 16 22  4 25]
 [18 14  9 18 22]
 [ 7  9 12 19 21]
 [ 1  2  8 22  2]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [10]:
array=np.random.randint(1,25,size=(5,5))
print(array)

corner_element=array[[0,0,-1,-1],[0,-1,0,-1]]
print(corner_element)

[[ 6 17 19 19 18]
 [21  2 21 13  8]
 [16 15  2 17  9]
 [10 24  7  4 18]
 [17 19  2 18  6]]
[ 6 18 17  6]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [12]:
array=np.random.randint(1,17,size=(4,4))
print(array)

array[array>10]=10
print(array)

[[ 2  1 14 10]
 [ 9  5  2  5]
 [16 16  9 14]
 [ 4  1 16 13]]
[[ 2  1 10 10]
 [ 9  5  2  5]
 [10 10  9 10]
 [ 4  1 10 10]]
